# Generated by Django 3.2.7 on 2021-12-28 20:00

import cpf_field.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0002_alter_candidates_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidates",
            name="age",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(19)],
                verbose_name="Idade",
            ),
        ),
        migrations.AlterField(
            model_name="candidates",
            name="cpf",
            field=cpf_field.models.CPFField(
                blank=True, max_length=14, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="candidates",
            name="immediate_availability",
            field=models.BooleanField(),
        ),
    ]
